# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "corundum"
  # The url from which the box will be fetched if it
  # doesn't already exist on the user's system.
  #
  # TODO: Point to distributed corundum image
  config.vm.box_url = "http://domain.com/path/to/corundum.box"

  # Change the hostname of project VM
  config.vm.host_name = "mydev"

  # Overrule port forwarding of guest:3000 to host:3000
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Boot the VM in a VirtualBox window. (Default is headless)
  #
  # Useful if using Vagrant on Windows so you can log into the VM directly
  #
  # Username and Password are both 'vagrant'
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
