#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Updating apt and build-essentials is required to build newer Rubies.
cookbook 'apt'
cookbook 'build-essential'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'nodejs',
  :git => 'https://github.com/mdxp/nodejs-cookbook'

cookbook 'mysql'
cookbook 'postgresql'


