#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Updating apt and build-essentials is required to build newer Rubies.
cookbook 'apt'
cookbook 'build-essential'

cookbook 'mysql'
